export {default as getCategories_API} from './getCategories'
export {default as getBestSeller_API} from './getBestSeller'
export {default as getPopularCategories_API} from './getPopularCategories'
export {default as getProductsByCategory_API} from './getProductsByCategory'
export {default as getPromo_API} from './getPromo'
